### ISSUE TITLE
Request a new certificate

### ISSUE THREAD

**Issue by webiandevteam** [webiandevteam/cusi.cis#4]
![image](https://user-images.githubusercontent.com/63875887/79634194-a4e08600-8186-11ea-8932-07edcbe0ee13.png)

change the "preview" button to "Preview" change the "Create Copy" button to "Create copy"

![image](https://user-images.githubusercontent.com/63875887/79634207-add15780-8186-11ea-93ed-8c4ff20e7fa5.png)

For Organic EU TC, when Box 7 Relation is selected, The country of box 7 is displayed in Box 8. If Box 9 Relation is selected, the country of box 9 is displayed in Box 8.

When the TC is confirmed, the values displayed will be same as mentioned above. which is not working like this now

**Comment by kshitijadalvi** [comment]
issues resolved.

**Comment by webiandevteam** [comment]
![image](https://user-images.githubusercontent.com/63875887/79636947-0578be80-8199-11ea-9899-d4ac0bd02963.png)
Arrange the error msg. and keep the red line full .. same like the below.

![image](https://user-images.githubusercontent.com/63875887/79636975-280ad780-8199-11ea-9b61-958d2d6bf0b8.png)


Onclick of delete button, call alert box and then delete.

**Comment by webiandevteam** [comment]
![image](https://user-images.githubusercontent.com/63875887/79637055-9780c700-8199-11ea-9749-da09340c3771.png)

Still the "P" of preview is small. make it caps. and also for Create Copy.. "C" small

**Comment by kshitijadalvi** [comment]
> ![image](https://user-images.githubusercontent.com/63875887/79637055-9780c700-8199-11ea-9749-da09340c3771.png)
> 
> Still the "P" of preview is small. make it caps. and also for Create Copy.. "C" small

i had done that part...plz first u merge the branch and check

**Comment by webiandevteam** [comment]
> > ![image](https://user-images.githubusercontent.com/63875887/79637055-9780c700-8199-11ea-9749-da09340c3771.png)
> > Still the "P" of preview is small. make it caps. and also for Create Copy.. "C" small
> 
> i had done that part...plz first u merge the branch and check

I pulled the branch 9-request-a-new-certificate.
In this , it is not there.
I can merge the branch in master before all possibilities are resolved.

**Comment by kshitijadalvi** [comment]
> > > ![image](https://user-images.githubusercontent.com/63875887/79637055-9780c700-8199-11ea-9749-da09340c3771.png)
> > > Still the "P" of preview is small. make it caps. and also for Create Copy.. "C" small
> > 
> > 
> > i had done that part...plz first u merge the branch and check
> 
> I pulled the branch 9-request-a-new-certificate.
> In this , it is not there.
> I can merge the branch in master before all possibilities are resolved.

i pushed the branch 2 times may b that's why this happen...i will solved

**Comment by webiandevteam** [comment]
ok

**Comment by kshitijadalvi** [comment]
all issues resolved

**Comment by webiandevteam** [comment]
![image](https://user-images.githubusercontent.com/63875887/79640746-d79f7400-81b0-11ea-89f4-46e173922df7.png)
@kshitijadalvi only five products are allowed to add

**Comment by kshitijadalvi** [comment]
@webiandevteam done

**Comment by webiandevteam** [comment]
Ok

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by webiandevteam** [comment]
done
